services:
  mysql-db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: definitions
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysql -ptest123 -e 'select 1'"]
      interval: 5s
      retries: 50

#api container 
  api:
    build: ./api
    ports:
      - "80:3000"   # for smoke test , from 80 to 3000
    environment:
      PORT: 3000
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: test123
      DB_NAME: definitions
      DB_CONN_LIMIT: 10
    depends_on:
      mysql-db:
        condition: service_healthy
